### ISSUE TITLE
Missing VS project files

### ISSUE THREAD

**Issue by nvisionative** [DNNCommunity/DNN.IFrame#1]
@EPTamminga - the VS project files seem to be missing on this project.  Can you please advise?  Thanks!

**Comment by EPTamminga** [comment]
There was no .sln file on the original CodePlex project. Just create an empty solution DNN.Iframe.sln and add all the files?

**Comment by nvisionative** [comment]
The missing .sln file is not really a problem - it's the missing .vbproj file that is more of the concern.

**Comment by EPTamminga** [comment]
I do not think that anything special is needed. Just start eith a new .vbproj project and add existimg items.

**Comment by nvisionative** [comment]
Okay, thanks.
