### ISSUE TITLE
Unable to embed a url 

### ISSUE THREAD

**Issue by pmetla** [DNNCommunity/DNN.IFrame#10]
i'm trying to embed a url to website built on top of DNN using iFrame module(DNN.IFrame 08.00.02) but it says that the url is not valid. when i tried embedding the same url using former versions of iFrame(4.4.0), it worked fine. This is the url i'm trying to embed "https://platform.remix.com/map/994739e?latlng=43.10473,-77.4392,
![untitled](https://user-images.githubusercontent.com/22299398/36808639-a983df36-1c93-11e8-8fce-ac8434386853.png)
z10.5". Thanks in advance!

**Comment by nvisionative** [comment]
@pmetla it is hard to see the URL correctly due to the embedded image, but is it the following?

```https://platform.remix.com/map/994739e?latlng=43.10473,-77.4392,z10.5```

If so, it seems this should pass validation just fine according to the REGEX pattern update in the last release.  [Here is a link for testing your URL](https://regex101.com/r/WCwPxJ/1) against the REGEX pattern used in the code.

**Comment by pmetla** [comment]
Yes, that's the url i'm trying to embed. "https://platform.remix.com/map/994739e?latlng=43.10473,-77.4392,z10.5" so strange why it says that the url is invalid. is there any other way to fix this?

**Comment by nvisionative** [comment]
Okay, we believe it is the commas that is throwing it off.  In closer examination of the test above, we see the URL is being truncated.  We will make a pull request to update the REGEX pattern to accept commas as well.

**Comment by nvisionative** [comment]
@pmetla this issue has been closed because our pull request was merged.  A new install package will need to be generated for you to upgrade to the new version.  @MaiklT will you be able to package a new release or is this just in queue for the next scheduled release?  Thanks!

**Comment by MaiklT** [comment]
Thanks to @nvisionative for caring about the regex, this is not my strength :-)

I thought about this returning problem of regular expressions that do not meet with some web sites. Now you can turn off the validation if you run into some error like this.

**Comment by pmetla** [comment]
It worked fine now. Thanks a bunch! @nvisionative @MaiklT
