### ISSUE TITLE
After DNN 9.4.0 upgrade - IFrame (8.1.1) fails

### ISSUE THREAD

**Issue by PatMcK** [DNNCommunity/DNN.IFrame#20]
## Describe the bug
Error: UserReg - FIGU in a Nutshell is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Value cannot be null. Parameter name: source ---> System.ArgumentNullException: Value cannot be null. Parameter name: source at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source) at DotNetNuke.Modules.IFrame.UI.IFrame.get_Source() at DotNetNuke.Modules.IFrame.UI.IFrame.Page_Load(Object sender, EventArgs e) --- End of inner exception stack trace -

## To Reproduce
1. Go to 'https://creationaltruth.org/Home/Website-User-Registration'
2. See error

## Expected behavior
IFrame should appear with selected pdf file displayed instead error shows up.

**Comment by MaiklT** [comment]
Cannot reproduce. It works as expected.

On a desktop PC, I see the PDF with Chrome, Firefox and Edge. On mobile devices, the PDF is not displayed, but a button is there to download it or the permission to download the file automatically is requested.

Seems to be browser behaviour/security settings.
