### ISSUE TITLE
Source Validation do not validate port number

### ISSUE THREAD

**Issue by giovaboy** [DNNCommunity/DNN.IFrame#23]
Hi, I've find out that the validator algorithm does not accept port defined in URL.
Ex.: http://localhost.com:8080/

This regex should make it work as intended
http(s)?:\/\/([\w-]+\.)+[\w-]+(:\d+)?(\/[\w- .\/?%&amp;=,!+]*)?

I've also find out that the validation does occour also if the check-box is flagged.
To reproduce this last issue:
1. Define an invalid URL (with port number) 
2. Check the 'Ignore source validation' checkbox
3. Update and exit
4. Enter again in edit mode, the box is flagged
5. Update and exit and notice the URL validator behaviour

Thank you.

**Comment by MaiklT** [comment]
I cannot reproduce this behavior. When activating the checkbox ("Ignore source validation?"), any Url is accepted. Which DNN version and which version of the module are you using?

**Comment by giovaboy** [comment]
DNN PLATFORM
v. 09.02.02 (178)
Module Version 8.1.0.0

**Comment by MaiklT** [comment]
Have you tried upgrading to the latest module version?

**Comment by giovaboy** [comment]
My fault, it was fixed in 08.01.01

**Comment by MaiklT** [comment]
Good... :-)

**Comment by MaiklT** [comment]
@david-poindexter : could you have a look at the regex, please?

**Comment by giovaboy** [comment]
The regex on the first post will actually fail on http://localhost:8080

This one should be better:
`http(s)?:\/\/([\w-]+\.?)+[\w-]+(:\d+)?(\/[\w- .\/?%&amp;=,!+]*)?`

**Comment by MaiklT** [comment]
I would not consider localhost - there is the "Ignore validation" option for that kind of usecases.
