### ISSUE TITLE
Failure A dependent component is not installed - System.Data.SqlClient.SqlColumnEncryptionEnclaveProvider

### ISSUE THREAD

**Issue by D0rk80** [DNNCommunity/DNN.IFrame#24]
DNN 90202
trying to install 
DotNetNuke.Modules.IFrame.08.01.02.pa

StartJob Reading files

Info File App_LocalResources\IFrame.ascx.resx read successfully
Info File App_LocalResources\IFrameOptions.ascx.resx read successfully
Info File App_LocalResources\SharedResources.resx read successfully
Info File bin\DotNetNuke.Modules.IFrame.dll read successfully
Info File DNN_IFrame.dnn read successfully
Info File Documentation\License.html read successfully
Info File Documentation\ReleaseNotes.html read successfully
Info File IFrame.ascx read successfully
Info File IframeOptions.ascx read successfully
Info File images\icon_iframe_16px.png read successfully
Info File images\icon_iframe_32px.png read successfully
Info File Module.css read successfully
Info File Providers/DataProviders/SqlDataProvider\03.02.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\04.03.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\08.00.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\UnInstall.SqlDataProvider read successfully
EndJob Reading files done.
StartJob Reading Installation Manifest file
Info Reading Package Manifest - Module - DNN_IFrame
Failure A dependent component is not installed - System.Data.SqlClient.SqlColumnEncryptionEnclaveProvider

**Comment by jncraig** [comment]
Just a wild guess, but do you have .NET 4.7.2 installed?

**Comment by MaiklT** [comment]
@jncraig is right. The module needs .Net 4.7.2 or higher since version 8.1.2 (see Releases). The type dependency for "System.Data.SqlClient.SqlColumnEncryptionEnclaveProvider" is used to check this, as it was introduced with this framework version.
