### ISSUE TITLE
Old DLLs not cleaned up during upgrade installation

### ISSUE THREAD

**Issue by nvisionative** [DNNCommunity/DNN.IFrame#4]
I just upgraded from IFrame 03.02.03 to 04.05.00 and the upgrade was successful.  However, upon visiting a page with an instance of the IFrame module on it, it would throw an exception as follows:

\DesktopModules\IFrame\IFrame.ascx.vb(58): error BC30560: 'Controller' is ambiguous in the namespace 'DotNetNuke.Modules.IFrame'.

From there, I decided to look at the DLLs in the bin folder and noticed they had not changed upon upgrade.  Therefore, I removed them and performed a "Repair" install on the module.  That fixed it and no new DLLs are even used in this module anymore it seems.  ;-)

**Comment by moorecreative** [comment]
Thank you David!

This write up helped me with an iframe similar issue when installing on Evoq 8 and encountering a bricked site after... to anyone else landing here by google search, if you need to uninstall the older iFrame 4.5.0 from a bricked site, you do so by:
1. in the App_Code folder, remove the "IFrame" folder
2. in the web.config, comment out the "codeSubDirectories" section of "Add directoryName=IFrame"
3. restart the site

**Comment by nvisionative** [comment]
You are welcome Ryan.  I am glad this helped.
