### ISSUE TITLE
Getting an invald URL error in DNN9.1.1

### ISSUE THREAD

**Issue by damirt2017** [DNNCommunity/DNN.IFrame#5]
This URL use to work fine using the iFrame module on DNN 7. I tried it on the DNN 9.1.1 and I am getting an invalid URL error. We use links like this to show a Google map on pages.

https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3192.788816874289!2d-76.29352088440305!3d36.847533472732984!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89ba980c600a4aad%3A0x7d2f74977acdd0af!2s150+Granby+St%2C+Norfolk%2C+VA+23510!5e0!3m2!1sen!2sus!4v1512680540910

![image](https://user-images.githubusercontent.com/34356526/33745007-38315e32-db69-11e7-9d8d-6cc5fb46be45.png)

**Comment by nvisionative** [comment]
We just made a pull request to correct this issue.  It appears the regex ValidationExpression for that field was not properly escaped.

**Comment by nvisionative** [comment]
By the way, here is a [regex validator](https://regex101.com/r/fx6EYt/1) to show how this works now...

**Comment by damirt2017** [comment]
Thank you for the quick response on this issue.

**Comment by nvisionative** [comment]
You are welcome.  We’ll need the repo owner @EPTamminga to merge the PR though and cread a new release.  Otherwise, you can modify the file manually.

**Comment by EPTamminga** [comment]
@nvisionative I am more than happy if I can share the required access to the repo to others who are willing to take responsibility for managing this module.

**Comment by nvisionative** [comment]
@EPTamminga we are doing a lot right now, but we’ll glady take on responsibility for this repo.

**Comment by nvisionative** [comment]
@EPTamminga we are doing a lot right now, but we’ll glady take on responsibility for this repo.  Thanks for all the work you have done to get these old core modules current.  You are a DNN Rockstar!

**Comment by EPTamminga** [comment]
@nvisionative Thank you for your support. 
I think I have added you to this repository with the necessary rights. Give it a try?

**Comment by nvisionative** [comment]
@EPTamminga thanks!  We now appear as a **Collaborator** for this repo, so I think we are good to go.

**Comment by nvisionative** [comment]
@damirt2017 thanks to @MaiklT there is now a [release package](https://github.com/DNNCommunity/DNN.IFrame/releases/tag/08.00.01) for this module that includes this fix.  I will go ahead and mark this issue as closed, but of course let us know if you run into any issues.

**Comment by damirt2017** [comment]
I am still getting the validation error. One of my colleagues suggested that the pattern needs to be changed to this: http(s)?:\/\/([\w-]+\.)+[\w-]+(\/[\w- .\/?%&amp;=!+]*)? 

This would allow ! and + characters in the URL. Can someone please review this?

**Comment by nvisionative** [comment]
@damirt2017 yes, seems we missed support for **!** and **+** characters.  We will add that shortly for you.  Here is the corrected regex pattern:

**http(s)?:\/\/([\w-]+\.)+[\w-]+(\/[\w- .\/?%&amp;=!+]*)?**

And here is a [link to the corrected regex test using your gmap embed URL](https://regex101.com/r/fx6EYt/2).  The one supplied has the same escaping issue as we discovered before.  :)

**Comment by nvisionative** [comment]
@MaiklT would you like to review #7 and create a new release?

**Comment by damirt2017** [comment]
Awesome. Thanks guys

**Comment by MaiklT** [comment]
@nvisionative I will...

**Comment by nvisionative** [comment]
@damirt2017 a [new release](https://github.com/DNNCommunity/DNN.IFrame/releases/tag/08.00.02) is now available thanks to @MaiklT - give it a spin and let us know if you have any more issues.  Hopefully we got it cleared up now.  :)
