### ISSUE TITLE
Issue when language of dnn is not the default english us one 

### ISSUE THREAD

**Issue by ThaProgrammingPuup** [DNNCommunity/DNN.IFrame#8]
Hi guys,

I faced an issue when i wanted to install the module on an dnn-website with a standard other language,
can i just add the additional resx files made for the other languages, or is there an other way?

Thanks in advance, else its a very handy module

**Comment by nvisionative** [comment]
@ThaProgrammingPuup you should be able to just add the appropriate RESX file(s).
