### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by heyepic** [DNNCommunity/DNN.IFrame#9]
I'm attempting to install this on DNN 9.1.1 and I'm getting this error:

`StartJob Reading files
Info File .gitignore read successfully
Info File App_LocalResources\EditIFrame.ascx.resx read successfully
Info File App_LocalResources\IFrame.ascx.resx read successfully
Info File App_LocalResources\IFrameOptions.ascx.resx read successfully
Info File App_LocalResources\SharedResources.resx read successfully
Info File Components\IFrameBase.cs read successfully
Info File Components\ParametersController.cs read successfully
Info File Components\ParametersInfo.cs read successfully
Info File DNN_IFrame.dnn read successfully
Info File Documentation\License.html read successfully
Info File Documentation\ReleaseNotes.html read successfully
Info File IFrame.ascx read successfully
Info File IFrame.ascx.cs read successfully
Info File IFrame.ascx.designer.cs read successfully
Info File IFrame.csproj read successfully
Info File IframeOptions.ascx read successfully
Info File IframeOptions.ascx.cs read successfully
Info File IframeOptions.ascx.designer.cs read successfully
Info File images\icon_iframe_16px.png read successfully
Info File images\icon_iframe_32px.png read successfully
Info File LICENSE read successfully
Info File Module.css read successfully
Info File packages.config read successfully
Info File Properties\AssemblyInfo.cs read successfully
Info File Providers/DataProviders/SqlDataProvider\03.02.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\04.03.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\08.00.00.SqlDataProvider read successfully
Info File Providers/DataProviders/SqlDataProvider\UnInstall.SqlDataProvider read successfully
Info File README.md read successfully
EndJob Reading files done.
StartJob Reading Installation Manifest file
Info Reading Package Manifest - Module - DNN_IFrame
Info Reading Component Manifest - Config
Info Reading Component Manifest - Cleanup
Info Reading Component Manifest - Cleanup
Info Reading Component Manifest - Script
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 03.02.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 04.03.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 08.00.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for Uninstall.SqlDataProvider.
Info Reading Component Manifest - Module
Info Module Manifest read successfully
Info Reading Component Manifest - Assembly
Failure File specified in the dnn could not be found in the zip file: - **C:\websites\Evoq\Install\Temp\1ugfykzm\bin\DotNetNuke.Modules.IFrame.dll**
Info Reading Component Manifest - File
Info Found valid path () for DNN_IFrame.dnn.
Info Found valid path () for IFrame.ascx.
Info Found valid path () for IFrameOptions.ascx.
Info Found valid path () for Module.css.
Info Found valid path (App_LocalResources) for IFrame.ascx.resx.
Info Found valid path (App_LocalResources) for IFrameOptions.ascx.resx.
Info Found valid path (App_LocalResources) for SharedResources.resx.
Info Found valid path (Documentation) for License.html.
Info Found valid path (Documentation) for ReleaseNotes.html.
Info Found valid path (images) for icon_iframe_16px.png.
Info Found valid path (images) for icon_iframe_32px.png.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 03.02.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 04.03.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for 08.00.00.SqlDataProvider.
Info Found valid path (Providers\DataProviders\SqlDataProvider) for Uninstall.SqlDataProvider.`

**Comment by nvisionative** [comment]
@heyepic we just successfully performed an install of IFrame 08.00.02 on a local instance of DNN 09.01.01 successfully (though it only officially supports DNN 8.x).  That said, error you are receiving seems to be a permissions related issue with your setup.  If you are working locally, you may want to utilize [nvQuickSite](http://www.nvquicksite.com) to make sure everything is setup correctly.
